HelpDeskProject/Controllers/HomeController.cs
using HelpDeskProject.Data;
using HelpDeskProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace HelpDeskProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly ApplicationDbContext _context;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            if (!User.Identity.IsAuthenticated)
            {

                return this.Redirect("~/identity/account/login");
            }
            else
            {
               var  tickets = await _context.Tickets.Include(t => t.CreatedBy).ToListAsync();

                return View(tickets);

            }
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HelpDeskProject/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HelpDeskProject.Data;
using HelpDeskProject.Models;
using System.Security.Claims;
using HelpDeskProject.Services;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Authorization;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;
using System.Xml.Linq;

namespace HelpDeskProject.Controllers
{

    [Authorize]
    public class TicketsController : Controller
    {
        private readonly ApplicationDbContext _context;
        public TicketsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Tickets
        public async Task<IActionResult> Index()
        {
            var tickets = await _context.Tickets.Include(t => t.CreatedBy).ToListAsync();

            return View(tickets);
        }

        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                .Include(t => t.CreatedBy)
                .FirstOrDefaultAsync(m => m.TicketID == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // GET: Tickets/Create
        public IActionResult Create()
        {
            ViewData["CreatedById"] = new SelectList(_context.Users, "Id", "FulllName");
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Ticket ticket)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            try
            {


                ticket.CreatedOn = DateTime.Now;
                ticket.CreatedById = userId;
                _context.Add(ticket);
                await _context.SaveChangesAsync();

                //Activity Logs
                var activity = new ActivityLog
                {
                    Action = "Create",
                    Timestamp = DateTime.Now,
                    BrowserInfo = Request.Headers["User-Agent"].ToString(),
                    IPAddress = HttpContext.Connection.RemoteIpAddress?.ToString(),
                    UserID = userId
                };
                _context.Add(activity);
                await _context.SaveChangesAsync();

                TempData["MESSAGE"] = "Ticket successfully created";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                //Error Logs
                var logs = new ErrorLog
                {
                    UserID = userId,
                    ErrorDescription = ex.Message,
                    LineNumber = 1,
                    IPAddress = HttpContext.Connection.RemoteIpAddress?.ToString(),
                    Traceback = ex.InnerException.ToString(),
                    Timestamp = DateTime.Now,
                    BrowserInfo = Request.Headers["User-Agent"].ToString(),
                };
                _context.Add(logs);
                await _context.SaveChangesAsync();
            }
            ViewData["CreatedById"] = new SelectList(_context.Users, "Id", "FulllName", ticket.CreatedById);
            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets.FindAsync(id);
            if (ticket == null)
            {
                return NotFound();
            }
            ViewData["CreatedById"] = new SelectList(_context.Users, "Id", "FulllName", ticket.CreatedById);
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Ticket ticket)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (id != ticket.TicketID)
            {
                return NotFound();
            }

            try
            {
                ticket.CreatedOn = DateTime.Now;
                ticket.CreatedById = userId;
                _context.Update(ticket);
                await _context.SaveChangesAsync();

                TempData["MESSAGE"] = "Ticket successfully Updated";

                //Activity Logs
                var activity = new ActivityLog
                {
                    Action = "Update",
                    Timestamp = DateTime.Now,
                    BrowserInfo = Request.Headers["User-Agent"].ToString(),
                    IPAddress = HttpContext.Connection.RemoteIpAddress?.ToString(),
                    UserID = userId
                };
                _context.Add(activity);
                await _context.SaveChangesAsync();

            }
            catch (Exception ex)
            {
                //Error Logs
                var logs = new ErrorLog
                {
                    UserID = userId,
                    ErrorDescription = ex.Message,
                    LineNumber = 1,
                    IPAddress = HttpContext.Connection.RemoteIpAddress?.ToString(),
                    Traceback = ex.InnerException.ToString(),
                    Timestamp = DateTime.Now,
                    BrowserInfo = Request.Headers["User-Agent"].ToString(),
                };
                _context.Add(logs);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
            ViewData["CreatedById"] = new SelectList(_context.Users, "Id", "FulllName", ticket.CreatedById);
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                .Include(t => t.CreatedBy)
                .FirstOrDefaultAsync(m => m.TicketID == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var ticket = await _context.Tickets.FindAsync(id);
            if (ticket != null)
            {
                // Remove all the comments
                var comments = await _context.Comments.Where(x=>x.TicketID==id).ToListAsync();
                _context.Comments.RemoveRange(comments);
                await _context.SaveChangesAsync();


                _context.Tickets.Remove(ticket);
                await _context.SaveChangesAsync();

                TempData["MESSAGE"] = "Ticket successfully Deleted";
            }

            //Activity Logs
            var activity = new ActivityLog
            {
                Action = "Delete",
                Timestamp = DateTime.Now,
                BrowserInfo = Request.Headers["User-Agent"].ToString(),
                IPAddress = HttpContext.Connection.RemoteIpAddress?.ToString(),
                UserID = userId
            };
            _context.Add(activity);
            await _context.SaveChangesAsync();


            return RedirectToAction(nameof(Index));

        }

        private bool TicketExists(int id)
        {
            return _context.Tickets.Any(e => e.TicketID == id);
        }
    }
}

HelpDeskProject/Views/Home/Index.cshtml
@model IEnumerable<HelpDeskProject.Models.Ticket>

@{
    ViewData["Title"] = "Help Desk Dashboard";
}
<div class="row row-cols-1 row-cols-lg-2 row-cols-xl-2 row-cols-xxl-4">
    <div class="col">
        <div class="card overflow-hidden rounded-4">
            <div class="card-body p-2">
                <div class="d-flex align-items-stretch justify-content-between  rounded-4 overflow-hidden bg-pink">
                    <div class="w-50 p-3">
                        <p class="text-white">Total Tickets</p>
                        <h4 class="text-white">8,542</h4>
                    </div>
                    <div class="w-50 p-3">
                        <p class="mb-3 text-white text-end">+ 16% <i class="bi bi-arrow-up"></i></p>
                        <div id="chart1"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card overflow-hidden  rounded-4">
            <div class="card-body p-2">
                <div class="d-flex align-items-stretch justify-content-between rounded-4 overflow-hidden bg-purple">
                    <div class="w-50 p-3">
                        <p class="text-white">Urgent Tickets</p>
                        <h4 class="text-white">12.5M</h4>
                    </div>
                    <div class="w-50  p-3">
                        <p class="mb-3 text-white text-end">- 3.4% <i class="bi bi-arrow-down"></i></p>
                        <div id="chart2"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card overflow-hidden rounded-4">
            <div class="card-body p-2">
                <div class="d-flex align-items-stretch justify-content-between rounded-4 overflow-hidden bg-success">
                    <div class="w-50 p-3">
                        <p class="text-white">Closed Tickets</p>
                        <h4 class="text-white">$64.5K</h4>
                    </div>
                    <div class="w-50 p-3">
                        <p class="mb-3 text-white text-end">+ 24% <i class="bi bi-arrow-up"></i></p>
                        <div id="chart3"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card overflow-hidden rounded-4">
            <div class="card-body p-2">
                <div class="d-flex align-items-stretch justify-content-between rounded-4 overflow-hidden bg-orange">
                    <div class="w-50 p-3">
                        <p class="text-white">Escalated Tickets</p>
                        <h4 class="text-white">25.8K</h4>
                    </div>
                    <div class="w-50 p-3">
                        <p class="mb-3 text-white text-end">+ 8.2% <i class="bi bi-arrow-up"></i></p>
                        <div id="chart4"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><!--end row-->



<div class="card rounded-4">
    <div class="card-body">
        <div class="d-flex align-items-center">
            <h6 class="mb-0">Recent Tickets</h6>
        </div>

        <div class="table-responsive mt-2">
            <table class="table align-middle mb-0">
                <thead class="table-light">
                    <tr>
                        <th>#ID</th>
                        <th>
                            @Html.DisplayNameFor(model => model.Title)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Description)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Status)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Priority)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CreatedBy)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CreatedOn)
                        </th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.TicketID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Title)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Status)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Priority)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CreatedBy.FulllName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CreatedOn)
                            </td>
                            <td>
                                <div class="d-flex align-items-center gap-3 fs-6">
                                    <a asp-action="Details" asp-route-id="@item.TicketID" asp-controller="Tickets" class="text-primary" data-bs-toggle="tooltip" data-bs-placement="bottom" title="" data-bs-original-title="View detail" aria-label="Views">
                                        <i class="bi bi-eye-fill"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>